[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "timur-xai"
version = "1.1.0"
authors = [
  { name="Neşet Koçkar" }
]
description = "Autonomous Dimensionless Physical Law Discovery and PINN Engine via Buckingham Pi"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "numpy",
    "torch",
    "scikit-learn",
    "scipy",
    "sympy",
    "pysr"
]

[project.urls]
"Homepage" = "https://github.com/Ne212/timur-xai"

[tool.setuptools.packages.find]
include = ["timur", "timur.*"]
